# ================== WireGuard Filter Config ==================

WGPORT="51234"                       # Porta UDP WireGuard
WAN_IF="eth0"                        # Interfaccia verso Internet della VM
HOSTS="saaay.mooo.com"               # Uno o più hostname DDNS separati da spazi
EXTRA_URL="https://discovery.lhcloud.it/wg0-acl.txt"  # Lista IP/CIDR extra
IPTABLES="/usr/sbin/iptables"
CHAIN="WG_FILTER"                    # Catena dedicata per la porta WG
